import os
import shutil
import json
import io
print("Copying Codes to client")
#DirCode = "../../UnityClient/Assets/Scripts/"
DirCode = "../../GoClient/"
#LuaDir = "../Assets/Scripts/NGameCode/Scripts/Lua/MufLibs/com.muf.network.client/sdplua"

for gofile in os.listdir('temp'):
    #if csfile.endswith('.go'):
        shutil.move('temp/' + gofile, DirCode + '/protocol/' + gofile)

#for luafile in os.listdir('temp/lua'):
#    if luafile.endswith('.bytes'):
#        shutil.move('temp/lua/' + luafile,  LuaDir + '/' + luafile)

#ProtoStr = "------------these code were generated by \"Protocol\GenerateClient.py\" do not edit it!!!------------ \n"
#ProtoStr += "gProtocol = {\n"
#CmdStr = ""
#MsgStr = ""
#with open("./src/desc.json", 'r') as load_f:
#    data = json.load(load_f)
#    for item in data:
#        id = str(item["id"])
#        NameStrArr = item["name"].split('.')
#        NameSpace = NameStrArr[0]
#        MsgName = NameStrArr[1]
#        CmdStr += "    Cmd_" + NameSpace + "_" + MsgName + "=" + id + ",\n"
#        MsgStr += "    [" + id + "]=" + "\"" + item["name"] + "\"" + ",\n"

#ProtoStr += (CmdStr + MsgStr)
#ProtoStr = ProtoStr[:-2]
#ProtoStr += "\n}\n\n"



startRead = False
errorCodeStr = ""
# with open("./src/errorCode.proto", 'r') as errorCodeRead:
for line in open("./src/errorCode.proto", 'r'):
    if "enum errorCode" in line:
        startRead = True
        line = line.replace("enum errorCode", "gErrorCode =")

    if startRead:
        errorCodeStr += line

errorCodeStr = errorCodeStr.replace("//", "--")
#ProtoStr += errorCodeStr

os.system("pause")

#file = open("../Assets/Scripts/Protocol/Protocol.lua", 'w', encoding='UTF-8')
#file.write(ProtoStr)
#file.close()

print("Copying done!")
